import { StyleSheet, Platform } from "react-native";
import { colors } from "../../../theme";

export const styles = StyleSheet.create({
  fab: {
    position: "absolute",
    bottom: Platform.OS === "ios" ? 100 : 90,
    right: 16,
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#6366F1",
    alignItems: "center",
    justifyContent: "center",
    elevation: 8,
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    zIndex: 9999,
  },
  fabPulse: {
    position: "absolute",
    top: 2,
    right: 2,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#22C55E",
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  panel: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "88%",
    overflow: "hidden",
  },
  panelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#EEF2FF",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  closeBtn: {
    padding: 4,
  },
  accountBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: "#F9FAFB",
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
    gap: 6,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#22C55E",
  },
  accountLabel: {
    fontSize: 11,
    color: colors.textSecondary,
    fontWeight: "500",
  },
  accountEmail: {
    fontSize: 11,
    color: colors.text,
    fontWeight: "700",
    flex: 1,
  },
  roleTag: {
    backgroundColor: "#E0E7FF",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  roleTagText: {
    fontSize: 9,
    color: "#4338CA",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  sectionTitle: {
    fontSize: 10,
    fontWeight: "800",
    color: colors.textMuted,
    letterSpacing: 1,
    marginBottom: 8,
  },
  helperText: {
    fontSize: 10,
    color: colors.textMuted,
    marginBottom: 4,
    lineHeight: 14,
  },
  helperHighlight: {
    fontSize: 10,
    color: "#4338CA",
    fontWeight: "600",
    marginBottom: 10,
    lineHeight: 14,
  },
  accountList: {
    gap: 6,
  },
  accountRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFFFFF",
  },
  accountRowActive: {
    borderColor: "#A5B4FC",
    backgroundColor: "#EEF2FF",
  },
  accountRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  avatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarActive: {
    backgroundColor: "#C7D2FE",
  },
  avatarText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.textSecondary,
  },
  avatarTextActive: {
    color: "#4338CA",
  },
  accountLabel2: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.text,
  },
  accountLabel2Active: {
    color: "#4338CA",
  },
  accountEmail2: {
    fontSize: 10,
    color: colors.textMuted,
  },
  activeBadge: {
    fontSize: 9,
    fontWeight: "800",
    color: "#6366F1",
    letterSpacing: 0.5,
  },
  errorBox: {
    marginTop: 8,
    backgroundColor: "#FEF2F2",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    flexDirection: "row",
    gap: 6,
    alignItems: "flex-start",
  },
  errorText: {
    flex: 1,
    fontSize: 11,
    color: "#DC2626",
  },
  categoryBox: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 8,
  },
  categoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#F9FAFB",
  },
  categoryTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.text,
  },
  categoryRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  categoryCount: {
    fontSize: 10,
    color: colors.textMuted,
    marginRight: 4,
  },
  scenarioRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
  },
  scenarioIconBox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  scenarioLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.text,
  },
  scenarioDesc: {
    fontSize: 11,
    color: colors.textMuted,
    lineHeight: 14,
    marginTop: 1,
  },
  resultBox: {
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 6,
    alignItems: "flex-start",
  },
  resultBoxOk: {
    backgroundColor: "#F0FDF4",
  },
  resultBoxErr: {
    backgroundColor: "#FEF2F2",
  },
  resultLabel: {
    fontSize: 11,
    fontWeight: "700",
  },
  resultMsg: {
    fontSize: 10,
    marginTop: 1,
  },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    backgroundColor: "#F9FAFB",
  },
  footerText: {
    fontSize: 10,
    color: colors.textMuted,
  },
  clearText: {
    fontSize: 10,
    color: "#EF4444",
  },
  passwordCard: {
    position: "absolute",
    top: "30%",
    left: 24,
    right: 24,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 20,
    elevation: 12,
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  passwordTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.text,
    marginBottom: 6,
  },
  passwordSubtitle: {
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: 14,
  },
  passwordInput: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: colors.text,
    marginBottom: 12,
  },
  passwordActions: {
    flexDirection: "row",
    gap: 8,
  },
  passwordBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: "center",
  },
  passwordBtnCancel: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFFFFF",
  },
  passwordBtnSave: {
    backgroundColor: "#6366F1",
  },
  passwordBtnTextCancel: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  passwordBtnTextSave: {
    fontSize: 13,
    fontWeight: "700",
    color: "#FFFFFF",
  },

  // ─── Seed settings styles ─────────────────────────────────────────
  settingsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  settingsHeaderTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.text,
  },
  customTag: {
    backgroundColor: "#EEF2FF",
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  customTagText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#6366F1",
    letterSpacing: 0.5,
  },
  settingsCard: {
    marginTop: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surface,
    gap: 8,
  },
  fieldLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  chipRow: {
    flexDirection: "row",
    gap: 6,
    marginBottom: 6,
  },
  chip: {
    flex: 1,
    paddingVertical: 7,
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    alignItems: "center",
  },
  chipActive: {
    borderColor: "#6366F1",
    backgroundColor: "#EEF2FF",
  },
  chipText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  chipTextActive: {
    color: "#6366F1",
    fontWeight: "700",
  },
  fieldRow: {
    flexDirection: "row",
    gap: 8,
  },
  fieldCell: {
    flex: 1,
  },
  fieldInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    fontSize: 12,
    color: colors.text,
    backgroundColor: colors.background,
    marginBottom: 4,
  },
  fieldMultiline: {
    minHeight: 48,
    textAlignVertical: "top",
  },
  resetText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#6366F1",
  },
  destructiveButton: {
    backgroundColor: "#DC2626",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 16,
    shadowColor: "#DC2626",
    shadowOpacity: 0.15,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  destructiveButtonText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#FFFFFF",
  },
});
